//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymGenius.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GymGenius.Api.Resources.SharedResource.es", typeof(SharedResource_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de sesión realizado con éxito.
        /// </summary>
        internal static string AuthControllerLoginOk {
            get {
                return ResourceManager.GetString("AuthControllerLoginOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro exitoso.
        /// </summary>
        internal static string AuthControllerRegisterOk {
            get {
                return ResourceManager.GetString("AuthControllerRegisterOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato del correo electrónico no es válido.
        /// </summary>
        internal static string AuthModelsEmailFormatInvalid {
            get {
                return ResourceManager.GetString("AuthModelsEmailFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico es obligatorio.
        /// </summary>
        internal static string AuthModelsEmailRequired {
            get {
                return ResourceManager.GetString("AuthModelsEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre debe tener al menos 2 caracteres.
        /// </summary>
        internal static string AuthModelsFirstNameMinLength {
            get {
                return ResourceManager.GetString("AuthModelsFirstNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre es obligatorio.
        /// </summary>
        internal static string AuthModelsFirstNameRequired {
            get {
                return ResourceManager.GetString("AuthModelsFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El apellido debe tener al menos 2 caracteres.
        /// </summary>
        internal static string AuthModelsLastNameMinLength {
            get {
                return ResourceManager.GetString("AuthModelsLastNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El apellido es obligatorio.
        /// </summary>
        internal static string AuthModelsLastNameRequired {
            get {
                return ResourceManager.GetString("AuthModelsLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña es obligatoria.
        /// </summary>
        internal static string AuthModelsPasswordRequired {
            get {
                return ResourceManager.GetString("AuthModelsPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener al menos 8 caracteres e incluir una mayúscula, una minúscula, un número y un carácter especial.
        /// </summary>
        internal static string AuthModelsPasswordTooWeak {
            get {
                return ResourceManager.GetString("AuthModelsPasswordTooWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario debe tener al menos 4 caracteres.
        /// </summary>
        internal static string AuthModelsUsernameMinLength {
            get {
                return ResourceManager.GetString("AuthModelsUsernameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario es obligatorio.
        /// </summary>
        internal static string AuthModelsUsernameRequired {
            get {
                return ResourceManager.GetString("AuthModelsUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere el nombre de usuario o el correo electrónico.
        /// </summary>
        internal static string AuthModelsUserOrEmailRequired {
            get {
                return ResourceManager.GetString("AuthModelsUserOrEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio de base de datos no está disponible temporalmente.
        /// </summary>
        internal static string DbUnavailable {
            get {
                return ResourceManager.GetString("DbUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rutina no encontrada.
        /// </summary>
        internal static string SplitsControllerNotFound {
            get {
                return ResourceManager.GetString("SplitsControllerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El orden del día debe ser válido.
        /// </summary>
        internal static string WorkoutModelsDayValid {
            get {
                return ResourceManager.GetString("WorkoutModelsDayValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre debe tener al menos 2 caracteres.
        /// </summary>
        internal static string WorkoutModelsNameMinLength {
            get {
                return ResourceManager.GetString("WorkoutModelsNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del entrenamiento es obligatorio.
        /// </summary>
        internal static string WorkoutModelsNameRequired {
            get {
                return ResourceManager.GetString("WorkoutModelsNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrenamiento añadido.
        /// </summary>
        internal static string WorkoutsControllerAdded {
            get {
                return ResourceManager.GetString("WorkoutsControllerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrenamiento eliminado con éxito.
        /// </summary>
        internal static string WorkoutsControllerDeleted {
            get {
                return ResourceManager.GetString("WorkoutsControllerDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrenamiento no encontrado.
        /// </summary>
        internal static string WorkoutsControllerNotFound {
            get {
                return ResourceManager.GetString("WorkoutsControllerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrenamiento actualizado con éxito.
        /// </summary>
        internal static string WorkoutsControllerUpdated {
            get {
                return ResourceManager.GetString("WorkoutsControllerUpdated", resourceCulture);
            }
        }
    }
}
