//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymGenius.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GymGenius.Api.Resources.SharedResource.fr", typeof(SharedResource_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le service de base de données est temporairement indisponible.
        /// </summary>
        internal static string DbUnavailable {
            get {
                return ResourceManager.GetString("DbUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme non trouvé.
        /// </summary>
        internal static string SplitNotFound {
            get {
                return ResourceManager.GetString("SplitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Séance ajoutée.
        /// </summary>
        internal static string WorkoutAdded {
            get {
                return ResourceManager.GetString("WorkoutAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Séance supprimée avec succès.
        /// </summary>
        internal static string WorkoutDeleted {
            get {
                return ResourceManager.GetString("WorkoutDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;ordre du jour doit être valide.
        /// </summary>
        internal static string WorkoutModelDayValid {
            get {
                return ResourceManager.GetString("WorkoutModelDayValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom doit comporter au moins 2 caractères.
        /// </summary>
        internal static string WorkoutModelNameMinLength2 {
            get {
                return ResourceManager.GetString("WorkoutModelNameMinLength2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom de la séance est obligatoire.
        /// </summary>
        internal static string WorkoutModelNameRequired {
            get {
                return ResourceManager.GetString("WorkoutModelNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Séance non trouvée.
        /// </summary>
        internal static string WorkoutNotFound {
            get {
                return ResourceManager.GetString("WorkoutNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Séance mise à jour avec succès.
        /// </summary>
        internal static string WorkoutUpdated {
            get {
                return ResourceManager.GetString("WorkoutUpdated", resourceCulture);
            }
        }
    }
}
