//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymGenius.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GymGenius.Api.Infrastructure.Serialization.SharedResource.en", typeof(SharedResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database service is temporarly unavailable.
        /// </summary>
        public static string DbUnavailable {
            get {
                return ResourceManager.GetString("DbUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split not found.
        /// </summary>
        public static string SplitNotFound {
            get {
                return ResourceManager.GetString("SplitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout added.
        /// </summary>
        public static string WorkoutAdded {
            get {
                return ResourceManager.GetString("WorkoutAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout successfully deleted.
        /// </summary>
        public static string WorkoutDeleted {
            get {
                return ResourceManager.GetString("WorkoutDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The day order must be valid.
        /// </summary>
        public static string WorkoutModelDayValid {
            get {
                return ResourceManager.GetString("WorkoutModelDayValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must be at least 2 characters long.
        /// </summary>
        public static string WorkoutModelNameMinLength2 {
            get {
                return ResourceManager.GetString("WorkoutModelNameMinLength2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workout name is required.
        /// </summary>
        public static string WorkoutModelNameRequired {
            get {
                return ResourceManager.GetString("WorkoutModelNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout not found.
        /// </summary>
        public static string WorkoutNotFound {
            get {
                return ResourceManager.GetString("WorkoutNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout successfully updated.
        /// </summary>
        public static string WorkoutUpdated {
            get {
                return ResourceManager.GetString("WorkoutUpdated", resourceCulture);
            }
        }
    }
}
