//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymGenius.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GymGenius.Api.Resources.SharedResource.de", typeof(SharedResource_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung erfolgreich.
        /// </summary>
        internal static string AuthControllerLoginOk {
            get {
                return ResourceManager.GetString("AuthControllerLoginOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrierung erfolgreich.
        /// </summary>
        internal static string AuthControllerRegisterOk {
            get {
                return ResourceManager.GetString("AuthControllerRegisterOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Format der E-Mail-Adresse ist ungültig.
        /// </summary>
        internal static string AuthModelsEmailFormatInvalid {
            get {
                return ResourceManager.GetString("AuthModelsEmailFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die E-Mail-Adresse ist erforderlich.
        /// </summary>
        internal static string AuthModelsEmailRequired {
            get {
                return ResourceManager.GetString("AuthModelsEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Vorname muss mindestens 2 Zeichen lang sein.
        /// </summary>
        internal static string AuthModelsFirstNameMinLength {
            get {
                return ResourceManager.GetString("AuthModelsFirstNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Vorname ist erforderlich.
        /// </summary>
        internal static string AuthModelsFirstNameRequired {
            get {
                return ResourceManager.GetString("AuthModelsFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Nachname muss mindestens 2 Zeichen lang sein.
        /// </summary>
        internal static string AuthModelsLastNameMinLength {
            get {
                return ResourceManager.GetString("AuthModelsLastNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Nachname ist erforderlich.
        /// </summary>
        internal static string AuthModelsLastNameRequired {
            get {
                return ResourceManager.GetString("AuthModelsLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Passwort ist erforderlich.
        /// </summary>
        internal static string AuthModelsPasswordRequired {
            get {
                return ResourceManager.GetString("AuthModelsPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Passwort muss mindestens 8 Zeichen lang sein und einen Großbuchstaben, einen Kleinbuchstaben, eine Zahl und ein Sonderzeichen enthalten.
        /// </summary>
        internal static string AuthModelsPasswordTooWeak {
            get {
                return ResourceManager.GetString("AuthModelsPasswordTooWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzername muss mindestens 4 Zeichen lang sein.
        /// </summary>
        internal static string AuthModelsUsernameMinLength {
            get {
                return ResourceManager.GetString("AuthModelsUsernameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzername ist erforderlich.
        /// </summary>
        internal static string AuthModelsUsernameRequired {
            get {
                return ResourceManager.GetString("AuthModelsUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername oder E-Mail-Adresse ist erforderlich.
        /// </summary>
        internal static string AuthModelsUserOrEmailRequired {
            get {
                return ResourceManager.GetString("AuthModelsUserOrEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Datenbankdienst ist vorübergehend nicht verfügbar.
        /// </summary>
        internal static string DbUnavailable {
            get {
                return ResourceManager.GetString("DbUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainingsplan nicht gefunden.
        /// </summary>
        internal static string SplitsControllerNotFound {
            get {
                return ResourceManager.GetString("SplitsControllerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Tagesreihenfolge muss gültig sein.
        /// </summary>
        internal static string WorkoutModelsDayValid {
            get {
                return ResourceManager.GetString("WorkoutModelsDayValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Name muss mindestens 2 Zeichen lang sein.
        /// </summary>
        internal static string WorkoutModelsNameMinLength {
            get {
                return ResourceManager.GetString("WorkoutModelsNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Name des Trainings ist erforderlich.
        /// </summary>
        internal static string WorkoutModelsNameRequired {
            get {
                return ResourceManager.GetString("WorkoutModelsNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training hinzugefügt.
        /// </summary>
        internal static string WorkoutsControllerAdded {
            get {
                return ResourceManager.GetString("WorkoutsControllerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training erfolgreich gelöscht.
        /// </summary>
        internal static string WorkoutsControllerDeleted {
            get {
                return ResourceManager.GetString("WorkoutsControllerDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training nicht gefunden.
        /// </summary>
        internal static string WorkoutsControllerNotFound {
            get {
                return ResourceManager.GetString("WorkoutsControllerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training erfolgreich aktualisiert.
        /// </summary>
        internal static string WorkoutsControllerUpdated {
            get {
                return ResourceManager.GetString("WorkoutsControllerUpdated", resourceCulture);
            }
        }
    }
}
